name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main", "release", "develop"]
    paths:
      - "app/**"
      - ".github/workflows/build.yml"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Run tests
        run: echo "TEST"